/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, arm, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/lex/Nimrod/lib -o /home/lex/nimrod/nimcache/hello.o /home/lex/nimrod/nimcache/hello.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <stdio.h>
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tcell42893 tcell42893;
typedef struct TNimType TNimType;
typedef struct tcellseq42909 tcellseq42909;
typedef struct tgcheap44816 tgcheap44816;
typedef struct tcellset42905 tcellset42905;
typedef struct tpagedesc42901 tpagedesc42901;
typedef struct tmemregion25210 tmemregion25210;
typedef struct tsmallchunk24438 tsmallchunk24438;
typedef struct tllchunk25204 tllchunk25204;
typedef struct tbigchunk24440 tbigchunk24440;
typedef struct tintset24415 tintset24415;
typedef struct ttrunk24411 ttrunk24411;
typedef struct tavlnode25208 tavlnode25208;
typedef struct tgcstat44814 tgcstat44814;
typedef struct TNimNode TNimNode;
typedef struct tbasechunk24436 tbasechunk24436;
typedef struct tfreecell24428 tfreecell24428;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  tcell42893  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq42909  {
NI Len;
NI Cap;
tcell42893** D;
};
struct  tcellset42905  {
NI Counter;
NI Max;
tpagedesc42901* Head;
tpagedesc42901** Data;
};
typedef tsmallchunk24438* TY25222[512];
typedef ttrunk24411* ttrunkbuckets24413[256];
struct  tintset24415  {
ttrunkbuckets24413 Data;
};
struct  tmemregion25210  {
NI Minlargeobj;
NI Maxlargeobj;
TY25222 Freesmallchunks;
tllchunk25204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk24440* Freechunkslist;
tintset24415 Chunkstarts;
tavlnode25208* Root;
tavlnode25208* Deleted;
tavlnode25208* Last;
tavlnode25208* Freeavlnodes;
};
struct  tgcstat44814  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap44816  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq42909 Zct;
tcellseq42909 Decstack;
tcellset42905 Cycleroots;
tcellseq42909 Tempstack;
NI Recgclock;
tmemregion25210 Region;
tgcstat44814 Stat;
};
typedef N_NIMCALL_PTR(void, TY2289) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2289 marker;
};
typedef NI TY24418[16];
struct  tpagedesc42901  {
tpagedesc42901* Next;
NI Key;
TY24418 Bits;
};
struct  tbasechunk24436  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk24438  {
  tbasechunk24436 Sup;
tsmallchunk24438* Next;
tsmallchunk24438* Prev;
tfreecell24428* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk25204  {
NI Size;
NI Acc;
tllchunk25204* Next;
};
struct  tbigchunk24440  {
  tbasechunk24436 Sup;
tbigchunk24440* Next;
tbigchunk24440* Prev;
NI Align;
NF Data;
};
struct  ttrunk24411  {
ttrunk24411* Next;
NI Key;
TY24418 Bits;
};
typedef tavlnode25208* TY25214[2];
struct  tavlnode25208  {
TY25214 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tfreecell24428  {
tfreecell24428* Next;
NI Zerofield;
};
N_NIMCALL(NimStringDesc*, readline_10884)(FILE* f);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell42893*, usrtocell_46442)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_48002)(tcell42893* c);
N_NOINLINE(void, addzct_46417)(tcellseq42909* s, tcell42893* c);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
N_NOINLINE(void, systemInit)(void);
N_NOINLINE(void, systemDatInit)(void);
N_NOINLINE(void, helloInit)(void);
N_NOINLINE(void, helloDatInit)(void);
STRING_LITERAL(TMP125, "What is your name? ", 19);
STRING_LITERAL(TMP126, "Hi, ", 4);
STRING_LITERAL(TMP127, "!", 1);
NimStringDesc* name_84004;
extern TFrame* frameptr_14038;
extern tgcheap44816 gch_44844;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_14038;
	frameptr_14038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_14038 = (*frameptr_14038).prev;
}

static N_INLINE(tcell42893*, usrtocell_46442)(void* usr) {
	tcell42893* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell42893*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell42893))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_48002)(tcell42893* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_46417(&gch_44844.Zct, c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell42893* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_46442(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell42893* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_46442((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_48002(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) (&locals));
	setStackBottom(locals);
}
void PreMain() {
	systemDatInit();
	systemInit();
	helloDatInit();
	initStackBottom();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMain)(void) {
	PreMain();
	helloInit();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_NOINLINE(void, helloInit)(void) {
	nimfr("hello", "hello.nim")
	nimln(1, "hello.nim");
	printf("%s\012", (((NimStringDesc*) &TMP125))->data);
	nimln(2, "hello.nim");
	asgnRefNoCycle((void**) &name_84004, readline_10884(stdin));
	nimln(3, "hello.nim");
	printf("%s%s%s\012", (((NimStringDesc*) &TMP126))->data, (name_84004)->data, (((NimStringDesc*) &TMP127))->data);
	popFrame();
}

N_NOINLINE(void, helloDatInit)(void) {
}

